# -*- coding: utf-8 -*-
"""descarga_genomas_cjejuni.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hrgAQ57SR7oBSYjh-N--vYMUu2-wYLC

# Descarga de genomas de Campylobacter jejuni desde NCBI

Este script automatiza la búsqueda y descarga de genomas completos desde la base de datos NCBI Assembly utilizando Biopython.

Autor: Valentina Mondragón
"""

!pip install biopython

!pip install biopython

from Bio import Entrez
import os
import urllib.request

Entrez.email = "valentinamondragon085@gmail.com"

from google.colab import drive
drive.mount('/content/drive')

output_dir = "/content/drive/MyDrive/TFM/Genomas_cjejuni"
os.makedirs(output_dir, exist_ok=True)

handle = Entrez.esearch(
    db="assembly",
    term="Campylobacter jejuni[Organism]",
    retmax=20
)

record = Entrez.read(handle)
print("Genomas encontrados:", len(record["IdList"]))
print(record["IdList"])

from Bio import Entrez

assembly_ids = record["IdList"]

links = []

for aid in assembly_ids:
    handle = Entrez.esummary(db="assembly", id=aid, report="full")
    summary = Entrez.read(handle)

    docsum = summary['DocumentSummarySet']['DocumentSummary'][0]

    ftp_path = docsum.get('FtpPath_RefSeq') or docsum.get('FtpPath_GenBank')

    if ftp_path:
        file_name = ftp_path.split('/')[-1]
        file_link = ftp_path + "/" + file_name + "_genomic.fna.gz"
        links.append(file_link)

print("Links encontrados:", len(links))
for l in links[:5]:
    print(l)

import os
import urllib.request

ruta = "/content/drive/MyDrive/TFM/Genomas_cjejuni"

os.makedirs(ruta, exist_ok=True)

for link in links:
    nombre = link.split("/")[-1]
    destino = os.path.join(ruta, nombre)

    print("Descargando:", nombre)
    urllib.request.urlretrieve(link, destino)

print("Descarga completa ✅")

handle = Entrez.esearch(
    db="assembly",
    term="Campylobacter jejuni[Organism]",
    retmax=120
)

record = Entrez.read(handle)
assembly_ids = record["IdList"]

print("Genomas encontrados:", len(assembly_ids))

links = []

for aid in assembly_ids:
    try:
        handle = Entrez.esummary(db="assembly", id=aid, report="full")
        summary = Entrez.read(handle)

        doc = summary['DocumentSummarySet']['DocumentSummary'][0]

        assembly_level = doc.get("AssemblyStatus", "")
        refseq = doc.get("FtpPath_RefSeq", "")

        # FILTRO
        if assembly_level in ["Complete Genome", "Chromosome"] and refseq:
            name = refseq.split("/")[-1]
            link = refseq + "/" + name + "_genomic.fna.gz"
            links.append(link)

    except Exception as e:
        print("Error:", e)

print("Genomas filtrados:", len(links))

for link in links:
    filename = link.split("/")[-1]
    filepath = os.path.join(output_dir, filename)

    if not os.path.exists(filepath):
        print("Descargando:", filename)
        urllib.request.urlretrieve(link, filepath)
    else:
        print("Ya existe (omitido):", filename)

print("✅ Descarga completa")

import gzip
import shutil
import os

output_dir = "/content/drive/MyDrive/TFM/Genomas_cjejuni"

for file in os.listdir(output_dir):
    if file.endswith(".gz"):
        gz_path = os.path.join(output_dir, file)
        out_path = os.path.join(output_dir, file.replace(".gz", ""))

        with gzip.open(gz_path, 'rb') as f_in:
            with open(out_path, 'wb') as f_out:
                shutil.copyfileobj(f_in, f_out)

print("✅ Archivos descomprimidos")

for file in os.listdir(output_dir):
    if file.endswith(".gz"):
        os.remove(os.path.join(output_dir, file))

print("🧹 .gz eliminados")

files = [f for f in os.listdir(output_dir) if f.endswith(".fna")]

print("Número de genomas:", len(files))
print("Ejemplo:", files[:5])

from Bio import SeqIO

file_path = os.path.join(output_dir, files[0])

for record in SeqIO.parse(file_path, "fasta"):
    print("ID:", record.id)
    print("Longitud:", len(record.seq))
    break

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/TFM/Genomas_cjejuni

ls *.fna | wc -l

ls | head

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# for f in *.fna; do
#   acc=$(echo $f | cut -d'_' -f1,2)
#   mv "$f" "${acc}.fna"
# done

!ls | head

!ls *.fna | wc -l

!apt-get update -y
!apt-get install mlst -y

!pip install -q condacolab
import condacolab
condacolab.install()

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/TFM/Genomas_cjejuni

ls *.fna | wc -l

!mamba install -c bioconda mlst -y

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# # Instalar mamba (gestor rápido)
# pip install -q condacolab
# python - <<EOF
# import condacolab
# condacolab.install()
# EOF